<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PRO" failures="1" tests="3" name="Error Validation" time="19.632" errors="0" timestamp="2022-11-18T18:52:21 IST">
  <testcase classname="pramodpoojary.SeleniumFrameworkDesign.errorValidation" name="errorMessageProdcut" time="2.333">
    <skipped/>
  </testcase> <!-- errorMessageProdcut -->
  <testcase classname="pramodpoojary.SeleniumFrameworkDesign.errorValidation" name="errorMessageProdcut" time="3.438">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pramodpoojary.SeleniumFrameworkDesign.errorValidation.errorMessageProdcut(errorValidation.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- errorMessageProdcut -->
  <testcase classname="pramodpoojary.SeleniumFrameworkDesign.errorValidation" name="errorMessageValidation" time="1.059"/>
</testsuite> <!-- Error Validation -->
